[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./prisma/"

[build.environment]
  NODE_VERSION = "20"
  # Configurações para o Prisma
  PRISMA_CLI_BINARY_TARGETS = "native,rhel-openssl-1.0.x"
  # Configurações para Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  # Certifique-se de que estas variáveis estão definidas no painel da Netlify
  # NEXT_PUBLIC_APPWRITE_ENDPOINT = "seu-endpoint-appwrite"
  # NEXT_PUBLIC_APPWRITE_PROJECT_ID = "seu-project-id-appwrite"
  # APPWRITE_API_KEY = "sua-api-key-appwrite"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"