[build]
  command = "npm run build:netlify"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"